FROM python:3.9-slim

WORKDIR /app

# Copier les fichiers du projet
COPY requirements.txt .
COPY application.py .
COPY xgb2_model.joblib .
COPY index.html .

# Créer le dossier templates
RUN mkdir -p templates

# Installer les dépendances
RUN pip install --no-cache-dir -r requirements.txt

# Installer Gunicorn pour le serveur de production
RUN pip install gunicorn

# Exposer le port utilisé par l'application
EXPOSE 5000

# Commande pour démarrer l'application avec Gunicorn
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "application:app"]